---
title: "Michael Leshchinsky's CV"
author: Michael Leshchinsky
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> [m.d.filbert@gmail.com](mailto:m.d.filbert@gmail.com)
- <i class="fab fa-linkedin"></i> [leshchinsky](https://www.linkedin.com/in/leshchinsky)
- <i class="fa fa-github"></i> [github.com/filbert42](https://github.com/filbert42)
- <i class="fa fa-phone"></i> 054-686-91-75


Skills {#skills}
--------------------------------------------------------------------------------

- ML productization, model and data monitoring and MLOps

- Data Science and Machine Learning infrastructure tools development

- ETL and data pipelines

- Statistical analysis, machine learning models, and optimization methods.

- Highly skilled in Python, R and SQL

- Also interested in functional languages, databases and distributed systems


Main
================================================================================

Michael Leshchinsky {#title}
--------------------------------------------------------------------------------

### Machine Learning Engineer | Data Scientist

I'm a Machine Learning Engineer with experience in Healthcare domain and passion for automation, MLOps, programming languages and best engineering practices

Professional Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Machine Learning Engineer \| MLOps Tech Lead

Clalit Research Institute \| Clalit Innovation

Ramat-Gan, Israel

2023 - 2021

-   Developed internal AutoML and MLOps tooling for the Data Science Team
-   Participated in the planning of the unit's long-term technological strategy and development
-   Developed new data infrastructure architecture for machine learning tasks
-   Documented infra systems and provided guidance for internal users.

### Data Scientist

Clalit Research Institute \| Clalit Innovation

Ramat-Gan, Israel

2021 - 2018

-   Created code for various research projects (Healthcare Economics, COVID-19, etc.)
-   Developed End-to-End prediction models for clinical interventions
-   Optimized data pipelines and processes, refactored legacy code

### Data Analyst, Business Intelligence

KIT Finance Capital

Saint Peterburg, Russia

2017 - 2016

- DevelopedT-SQL queries for reports and analytics 
- Developing scripting infrastructure in Python for data analysis and ETL
- Developed and tested KPI for various business processes
- Designed and performed monthly and quarter reports

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### St Petersburg University

M.S in Economics

Saint Petersburg, Russia

2016

### St Petersburg University

B.S. in Economics

Saint Petersburg, Russia

2014

Publications {data-icon=file}
--------------------------------------------------------------------------------

### Effectiveness of BNT162b2 Vaccine against Delta Variant in Adolescents

N Engl J Med 2021; 385:2101-2103

N/A

2021

Ben Y Reis, Noam Barda, Michael Leshchinsky, Eldad Kepten, Miguel A Hernán, Marc Lipsitch, Noa Dagan, Ran D Balicer
